version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'P@ssw0rd'
      POSTGRES_DB: navict-app-db
